config/routes.rb
Rails.application.routes.draw do



  root 'home#index'

  resources :orders

  resources :products

  resources :carts

  post 'carts/buy/:id', to: 'carts#buy', as: 'buycart'

  post 'carts/addproduct/:id', to: 'carts#addproduct', as: 'addtocart'

  post 'carts/removeproduct/:id', to: 'carts#removeproduct', as: 'removeproduct'

  get 'carts/show', to: 'carts#show'

  get 'products/index', to: 'products#index'

  devise_for :users
  get 'home/index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :customer, class_name: "User", foreign_key: "user_id"
	has_and_belongs_to_many :products, class_name: "Product"
	
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :client, class_name: "User", foreign_key: "user_id"
	has_and_belongs_to_many :products, class_name: "Product"
end

app/models/product.rb
class Product < ApplicationRecord
  
  has_and_belongs_to_many :carts, class_name: "Cart"
  has_and_belongs_to_many :orders, class_name: "Order"
  
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { in: 4..3000 }
  validates :price, presence:true, :numericality => {:greater_than_or_equal_to => 0}
  validates :image_url, presence:true

end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders, class_name: "Order"
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :sanitize_devise_parameters, if: :devise_controller?

  def sanitize_devise_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :sign_up_code])
  end

  def logged_in?
    !current_user.nil?
  end


  def ensure_login
    return true if logged_in?
    session[:return_to] = request.fullpath
    redirect_to new_user_session_path and return false
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :ensure_login

  def show
  	@cart = current_user.cart
  	@products = @cart.products
  end

  def addproduct
  	@cart = current_user.cart
  	@product = Product.find(params[:id])
    if (@cart.products).include? @product
      flash[:notice] = "Vous avez déjà acheté cette photo!"
      redirect_back(fallback_location: root_path)
    else
  	  @cart.products << @product
  	  @cart.save
      flash[:notice] = "La photo a bien été ajoutée à votre panier"
      redirect_back(fallback_location: root_path)
    end
  end

  def removeproduct
    @cart = current_user.cart
    @product = Product.find(params[:id])
    @cart.products.delete(@product)
    redirect_to @cart
  end



  def destroy
  	@cart = current_user.cart
  	@cart.destroy
  	redirect_to home_index_path

  end

  def buy

    require 'stripe'
    @cart = current_user.cart
    @products = @cart.products
    @sum = 0
    @products.each do |product|
      @sum += product.price
    end
    @amount = (@sum*100).to_i
    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )


    @order = Order.new
    @user = current_user
    @order.products = @products
    @user.orders << @order
    @user.save
    @order.save
    
    

    UserMailer.buy_email(@user, @products).deliver_now!
 #   UserMailer.emails_to_admins(@user, @products).deliver_now!

    @user.cart.destroy
    flash[:success] = "Merci pour votre achat, un mail récapitulatif de votre commande vous a été envoyé"

    redirect_to root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in? && !current_user.cart
    	@cart = Cart.new(name:"Mon Panier")
    	current_user.cart = @cart
    	@cart.save
    end
    @products = Product.all

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_login
  def index
  	@orders = current_user.orders
  end

  def show
  	@order = Order.find(params[:id])
  	@products = @order.products
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 5)
  end

  def show
  	@product = Product.find(params[:id])
    @products = Product.all
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb

<% @sumprices = 0 %>
    <!--breadcrumb start-->
        <div class="breadcrumb-wrapper">
            <div class="container">
                <h1><%= @cart.name %></h1>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="space-60"></div>
        <div class="container">
            <div class="table-responsive">
                <table class="table table-condensed cart-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Produit</th>
                            <th>Prix</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @products.each do |product| %>
                        <tr>
                              <td class="product-image"><%= image_tag(product.image_url, :atl => "", :width => 300, :height => 250, :crop => :fill) %></td>
                              <td class='product-name'><%= product.title %></td>
                              <td class="product-price"><%= product.price %></td>
                              <td class='product-delete'><%= link_to "Supprimer du panier", removeproduct_path(product), method: :post, :class => "btn btn-danger btn-xm" %></td>
                              <% @sumprices += product.price %>
                        </tr>
                        <% end %>
                    </tbody>
                </table><!--cart table-->
            </div>
            <div class="space-20"></div>
            <div class="coupon-row">
                <div class="row">
                    <div class="col-sm-4">
                    </div>
                </div>
            </div><!--cart row-->
            <div class="space-30"></div>
            <div class="cart-total">
                <div class="row">
                    <div class="col-sm-4 col-sm-offset-8">
                        <h2>Passer la commande</h2>
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                 <tr>
                                    <td>Livraison</td>
                                    <td>Gratuite par email</td>
                                </tr>
                                 <tr>
                                    <td>Total</td>
                                    <td class="total"><%=@sumprices%></td>
                                </tr>
                                <tr>
                                    <div>

                                </tr>
                            </tbody>
                        </table>
                        <%= form_tag buycart_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Montant total du panier :"
          data-amount="<%= @sumprices * 100 %>"
          data-currency="eur"
          data-locale="auto"></script>
<% end %>
  </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="space-60"></div>

app/views/layouts/_footer.html.erb
<!--footer start-->
<footer class="footer">
    <div class="container">
      <div class="row">
            <div class="col-md-3 margin-b-30">
                             <h3>A propos de nous</h3>
                             <p>
                                 Nous sommes une jeune pousse dans le commerce animalier et nous sortons tous d'une formation des familles: The Hacking Project!
                             </p>
                             <ul class="list-inline social-footer">
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Google plus"><i class="fa fa-google-plus"></i></a></li>
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Youtube"><i class="fa fa-youtube-play"></i></a></li>
                                 <li><a href="#" data-toggle="tooltip" data-placement="top" data-title="Rss feeds"><i class="fa fa-rss"></i></a></li>
                             </ul>
                         </div>
                         <div class="col-md-3 margin-b-30"></div>
                         <div class="col-md-3 margin-b-30"></div>

                         <div class="col-md-3 margin-b-30">
                             <h3>Contactez-nous</h3>
                             <div class="media">
                                 <div class="media-left">
                                     <i class="fa fa-phone"></i>
                                 </div>
                                 <div class="media-body">
                                     <h4 class="media-heading">+33 06 89 54 32 18</h4>
                                 </div>
                             </div>
                             <div class="media">
                                 <div class="media-left">
                                     <i class="fa fa-envelope"></i>
                                 </div>
                                 <div class="media-body">
                                     <h4 class="media-heading">chatons@minou.com</h4>
                                 </div>
                             </div>
                             <div class="media">
                                 <div class="media-left">
                                     <i class="fa fa-home"></i>
                                 </div>
                                 <div class="media-body">
                                     <h4 class="media-heading">Rue des serruriers,Strasbourg</h4>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </footer>
             <div class="footer-bottom">
                 <div class="container text-center">
                     <h3>Chat Paradise</h3>
                     <ul class="list-inline">
                         <li><a href="#">A propos</a></li>
                         <li><a href="#">Contact</a></li>
                         <li><a href="#">Nouveautés</a></li>
                     </ul>
                      &copy; Copyright 2018, Chat Paradise</span>
                 </div>
             </div>
             <!--footer end-->

app/views/layouts/_header.html.erb
<!--header start-->
  <header class="header">
      <!--top bar-->
      <div class="top-bar">
          <div class="container">
              <div class="row">
                  <div class="col-sm-6 hidden-xs">
                      <span>Bienvenue au paradis des chats</span>
                  </div>
                  <div class="col-sm-6 text-right">
                      <ul class="list-inline">
                          <% if user_signed_in? %>
                          <li class="hidden-xs"><a href="#" class="offers">Nouveau</a></li>
                          <li class="hidden-xs"><strong><%= current_user.username.capitalize %></strong></li>
                          <li class="hidden-xs"><%= link_to "Profil", edit_user_registration_path %></li>
                          <li class="hidden-xs"><%= link_to "Mes achats", orders_path %></li>
                          <li class="hidden-xs"><%=link_to "Mon panier", cart_path(current_user.cart) %></li>
                          <li class="hidden-xs"><%= link_to content_tag(:i, nil, class: 'pe-7s-user') + " Deconnexion ", destroy_user_session_path, :method => :delete %></li>
                          <% else %>
                          <li class="hidden-xs"><a href="#" class="offers">Nouveau</a></li>
                          <li class="hidden-xs"><%= link_to content_tag(:i, nil, class: 'pe-7s-user') + " S'inscrire ", new_user_registration_path %></li>
                          <li><%= link_to content_tag(:i, nil, class: 'pe-7s-lock') + " Connexion ", new_user_session_path %></li>
                          <% end %>
                  </div>
              </div>
          </div>
      </div>
      <!--top bar end-->


      <!--main navigation start-->
      <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-static-top yamm sticky">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <%= link_to(image_tag("cat-logoo.png", :alt => "logo", :class => "navbar-brand", :width => 70), root_path ) %>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                      <li class="active"><%= link_to "Accueil", root_path %></li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown" role="button" aria-haspopup="true">Chatons <i class="fa fa-angle-down"></i></a>
                          <ul class="dropdown-menu">
                              <li><%=link_to "Photos de chats", products_path %></li>
                          </ul>
                      </li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">

                    <% if user_signed_in? %>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown" role="button" aria-haspopup="true"><i class="pe-7s-cart"></i> <span class="badge"></span></a>
                          <div class="dropdown-menu shopping-cart">
                                <% 	@cart = current_user.cart %>
                                <% @cart_products = @cart.products %>
                                <% @cart_products.each do |product| %>
                                  <div class="cart-items content-scroll">
                                    <div class="cart-item clearfix">
                                      <div class="description">
                                          <%= product.title %><strong class="price"><%= product.price %></strong>
                                      </div><!--Description-->
                                      <div class="buttons">
                                          <a href="/products/<%=product.id%>" class="fa fa-pencil"></a><%=link_to content_tag(:i,nil, class: "fa fa-trash-o"), removeproduct_path(product), method: :post %>
                                      </div>
                                      <% end %>
                                      </div><!--cart item-->
                                    </div><!--cart-items-->
                                  </div><!--footer of cart-->
                          </div><!--cart dropdown end-->
                        <% end %>
                      </li>
                  </ul>
              </div><!--/.nav-collapse -->
          </div><!--/.container-fluid -->
      </nav>
      <!--main navigation end-->
      <!--main navigation end-->
  </header>
  <!--header end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProjetChatons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
    <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/index.html.erb
           <!--breadcrumb start-->
        <div class="breadcrumb-wrapper">
            <div class="container">
                <h1>Historique des achats</h1>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="space-60"></div>
        <div class="container">
            <div class="row">
                <h1>Voici la litre de vos commandes passées</h1>
            </div>
            	<% @orders.each do |order| %>
        		<% @products = order.products %>
        		<h3>Date de la commande : <%= order.created_at.strftime("le %d-%m-%Y à %HH%M") %></h3>
            <div class="table-responsive table-order-history">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Titre</th>
                            <th>description</th>
                            <th>Status</th>
                            <th>Pris</th>
                        </tr>
                    </thead>

                    <tbody>
                    		<% @products.each do |product| %>
                        <tr>
                            <td valign="middle"><%= image_tag product.image_url, :alt => "", :width => "150" %></td>
                            <td valign="middle"><%= product.title %></td>
                            <td valign="middle"><%= product.description %></td>
                            <td><span class="label-success"><i class="fa fa-check"></i></span> Success</td>
                            <td><%= product.price %></td>
                        </tr>
                        	<% end %>
                        </tbody>
                    </table>

                </div>
                <% end %>
            </div>

app/views/orders/show.html.erb
        <!--breadcrumb start-->
        <div class="breadcrumb-wrapper">
            <div class="container">
                <h1>Détails de la commande</h1>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="space-60"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                        Date de la commande : <%= @order.created_at %> 
                </div>
            </div>
            <div class="table-responsive table-order-history">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Titre</th>
                            <th>description</th>
                            <th>Status</th>
                            <th>Pris</th>
                        </tr>
                    </thead>

                    <tbody>
                    		<% @products.each do |product| %>
                        <tr>
                            <td valign="middle"><%= image_tag product.image_url, :alt => "", :width => "150" %></td>
                            <td valign="middle"><%= product.title %></td>
                            <td valign="middle"><%= product.description %></td>
                            <td><span class="label-success"><i class="fa fa-check"></i></span> Success</td>
                            <td><%= product.price %></td>
                        </tr>
                        	<% end %>
                        </tbody>
                    </table>
                </div>
            </div>
            



                            

app/views/products/index.html.erb
<!--breadcrumb start-->
        <div class="breadcrumb-wrapper">
            <div class="container">
                <h1>Chatons</h1>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="space-60"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <% @products.each do |product| %>
                    <div class="product-list">
                        <div class="row">
                            <div class="col-md-4 margin-b-30">
                                <div class="product-list-thumb">
                                    <%= image_tag product.image_url, alt:"Product image", class: "img-responsive"  %>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="product-list-desc">
                                    <h3 class="title"><%= product.title %></h3>
                                    <span class="price"><%= product.price%>€</span>
                                    <p>
                                        <%= product.description %>
                                    </p>
                                    <div class="icon-list">
                                      <%= link_to "Ajouter au panier", addtocart_path(product), method: :post, class: "btn btn-skin btn-lg" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!--products list-->
                    <!--pagination-->
                    <% end %>
                    <nav>
                        <ul class="pagination pull-right clearfix">
                            <li><%= will_paginate @products, renderer: BootstrapPagination::Rails %></li>
                        </ul>
                    </nav>
                    <!--pagination end-->
                </div>
            </div>
        </div>
        <div class="space-60"></div>

app/views/products/show.html.erb
        <!--breadcrumb start-->
        <div class="breadcrumb-wrapper">
            <div class="container">
                <h1>Détail de la photographie</h1>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="space-60"></div>
        <div class="container">
            <div class="row single-product">

                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-5 margin-b-30">
                            <div class="item">
                                <%= image_tag @product.image_url, alt:"Product image", class: "img-responsive"  %>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="product-detail-desc">
                                <h3 class="title"><%= @product.title %></h3>
                                <span class="price"><%= @product.price%>€</span>
                                <p>
                                    <%= @product.description %>
                                </p>
                                <div class="add-buttons">
                                    <%= link_to content_tag(:i,nil, class: "fa fa-shopping-cart") + "Ajouter au panier", addtocart_path, method: :post, class: "btn btn-skin btn-lg" %>
                                </div>
                            </div>
                        </div>
                    </div><!--single product details end-->
                    <div class="space-40"></div>
                    <div class="row">
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                </div>
            <div class="space-60"></div>
        </div>
    </div>
    <!--new arrivals-->
    <section class="new-arrivals">
        <div class="container">
            <h2 class="section-heading">Photographies récentes</h2>

            <!--owl carousel-->
            <div class="row">
                <div id="owl-slider" class="col-md-12 owl-carousel owl-theme">
                  <% @products.take(6).each do |product| %>
                    <div class="item">
                        <div class="item_holder">
                            <a href="/products/<%=product.id%>"><%= image_tag product.image_url, :alt => "", :class => "img-responsive" %></a>
                            <div class="title">
                                <h5><%= product.title%><br><%= product.description%></h5>
                                <span class="price"><%= product.price%>€</span>
                            </div>
                        </div><!--item holder-->
                    </div> <!--item loop-->
                    <% end %>

                </div>
            </div>
            <!--owl end-->
        </div>
    <script>
          $(document).ready(function(){
        $('.owl-carousel').owlCarousel({
          nav: true,
          navText: ["<span class='icon icon-arrow-left7'></span>","<span class='icon icon-arrow-right7'></span>" ]
        });
});
</script>